import { z, reference } from "astro:content";

export const writingSchema = z.object({
  id: z.string(),
  title: z.string(),
  description: z.string(),
  published: z.coerce.date(),
  updated: z.coerce.date().optional(),
  draft: z.boolean().default(false),
  featured: z.boolean().default(false),
  category: z.enum(["Essay", "Engineering", "Cybersecurity", "Field Notes", "Journal"]),
  tags: z.array(z.string()),
  series: z.string().optional(),
  seriesOrder: z.number().optional(),
  cover: z.string().optional(),
  coverAlt: z.string().optional(),
  coverWidth: z.number().optional(),
  coverHeight: z.number().optional(),
  author: reference('authors').optional(),
  toc: z.boolean().default(true),
  canonical: z.string().url().optional(),
  ogImage: z.string().optional(),
  difficulty: z.string().optional(),
  language: z.string().default("en"),
  related: z.array(z.string()).default([]),
  aliases: z.array(z.string()).default([]),
  keywords: z.array(z.string()).default([]),
  searchBoost: z.number().default(0),
  excludeFromSearch: z.boolean().default(false),
  version: z.number().default(1),
  revision: z.number().default(1),
  reviewed: z.coerce.date().optional(),
  lastReviewed: z.coerce.date().optional(),
  status: z.enum(["Draft", "Review", "Scheduled", "Published", "Archived", "Deprecated"]).default("Published"),
  priority: z.number().default(50),
  structuredData: z.boolean().default(true),
  changes: z.array(z.string()).default([])
});
